# Generated by Django 3.2.8 on 2023-08-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_coffee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coffee',
        ),
    ]
