# Generated by Django 3.2.8 on 2023-08-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_coffee'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
