# Generated by Django 3.2.8 on 2023-08-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
